/*
 * This source file was generated by the Gradle 'init' task
 */
package essence.of.oop.chapter01;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
